### ISSUE TITLE
# of upvotes hidden by default picture when viewing user page

### ISSUE THREAD

**Issue by andrewnguyen42** [reddit/reddit#1312] opened 2015-05-09 23:01 UTC
Broken version in Chrome/Firefox and with/without RES
http://imgur.com/krT5vqk

http://www.reddit.com/r/bugs/comments/35dgc7/of_upvotes_hidden_by_default_picture_when_viewing/

**Comment by DogPawHat** [comment] 2015-05-17 12:37
Took a look at this in chrome with RES and the developer tools. Can't replicate the bug on reddit.com with a different user:
![upvotes_not_hidden](https://cloud.githubusercontent.com/assets/2125961/7670277/133d93e8-fc96-11e4-904e-d351a37ab3a3.PNG)

From the dev tools I found this style applied to .midcol

    body >.content .link .midcol, .midcol-spacer {
      width: 5.1ex;
    }

Where I think the width is set server side depending on the number of upvotes of the most upvoted link. So if you had a user with a link with say only 9 upvotes, and you replaced that with 1234 in the developer tools, you would get the result above you had.

**Comment by allthefoxes** [comment] 2015-05-31 14:46
Related to #1172

**Comment by DogPawHat** [comment] 2015-06-01 10:22
I'd say its a full on duplicate of #1172

**Closed** 2015-06-02 19:01 UTC
