### ISSUE TITLE
Reddit 50/50 Down

### ISSUE THREAD

**Issue by dreadedkillerz** [reddit/reddit#1781] opened 2017-03-26 04:23 UTC
So I was trying to make a YouTube video on reddit 50/50 but the second page there was nothing there and only 6 of them wont make for much of a video, please fix so I can make the video

**Comment by akkatracker** [comment] 2017-03-26 09:44
2 Things:

1) FiftyFifty isn't down from what I can see - try again
2) Highly unlikely it's down because of the Reddit code here.

Can you give us some steps to reproduce?

Let me know if it still isn't working, otherwise can a member close this

**Comment by jedberg** [comment] 2017-03-26 17:03
This isn't the appropriate place for this bug report, but I was curious so I checked it out.

If you load up https://www.reddit.com/r/FiftyFifty/ with your cookies off, there is only 6 entries, and all of them are marked SFW.

So it's not a bug at all, but the fact that non-logged-in users don't see NSFW content by default on reddits without an 18-gate.

@dreadedkillerz Log in and you should see everything.

(I can't close this either but I'm sure someone from reddit will)

**Comment by zeantsoi** [comment] 2017-03-26 21:57
Thanks @jedberg, this is indeed expected behavior.

**Closed by zeantsoi** 2017-03-26 21:57 UTC
