### ISSUE TITLE
Tor API requests blocked with error 403

### ISSUE THREAD

**Issue by QuantumBadger** [reddit/reddit#1664] opened 2016-08-06 22:46 UTC
I've been receiving reports from users of my app (RedReader) that they're getting 403 errors when trying to connect to reddit using Tor:

https://github.com/QuantumBadger/RedReader/issues/290

I've tested this and can confirm the issue. Support for Tor was recently integrated directly into the app, and it appears that reddit blocks API requests from most Tor exit nodes. Exit nodes in Australia and New Zealand seem less likely to be blocked than others.

Is this intentional behaviour? I'm assuming it's just an automatic response to abuse from those IPs, but if nothing else it would make sense to whitelist exit node IPs for read-only access.

While I'm not a Tor user myself, many users are located in oppressive regimes with a high degree of censorship and surveillance, and it's important that their access to information is not curtailed in the name of anti-spam measures!

**Comment by Pokechu22** [comment] 2016-08-06 23:07
Is it possible that this is caused by rate-limiting due to a non-unique user agent?

**Comment by QuantumBadger** [comment] 2016-08-07 10:18
> Is it possible that this is caused by rate-limiting due to a non-unique user agent?

Thanks for the suggestion. The app recently switched to OkHTTP, and since the switch it looks like it was using the default user agent. I've now fixed this.

However, even with the unique user agent, I can still reproduce the 403 errors.

**Comment by 13steinj** [comment] 2016-08-07 14:48
@QuantumBadger Do you mind giving an example request and the related response (hiding sensitive data as necessary, of course).

**Comment by QuantumBadger** [comment] 2016-08-07 17:02
@SpotComms has been able to reproduce this with full OkHTTP logging turned on, and it appears that the problem is Cloudflare requiring the API client to complete a CAPTCHA:

https://gist.github.com/SpotComms/91fb6579664e32dd002009e0b527f2aa

So Cloudflare seems to be incorrectly set up to treat API requests as if the are from a web browser.

**Comment by 13steinj** [comment] 2016-08-08 04:39
Ugh, that sucks. You may want to post to /r/bugs for quicker attention, but I don't think it would do anything. A cursory look through cloudflare blogs show that it's either completely trust users (not ideal) or challenge / block them (not ideal either).

You may be able to solve it on your end (not in a pretty way, though). If there's something constant in these 403 responses, detect it, tell the user cloudflare wants a captcha cause they are using TOR, then [open the data in a webview](http://stackoverflow.com/questions/8987509/how-to-pass-html-string-to-webview-on-android), detect a change to mark success, and record any cookies that are set.

**Comment by QuantumBadger** [comment] 2016-08-08 17:46
/r/bugs post opened here:

https://www.reddit.com/r/bugs/comments/4wre66/cloudflare_blocks_reddit_api_requests_from_tor/

> open the data in a webview, detect a change to mark success, and record any cookies that are set

This is something I'd like to avoid if at all possible. The 403 errors can occur for any request, including the initial OAuth2 authentication (and token refreshes), and attempting to detect CloudFlare CAPTCHA responses would add a load of unnecessary complexity to the app. It would also be quite a poor user experience for Tor users.

**Comment by kjoconnor** [comment] 2016-08-08 18:47
I'm going to close this issue at as it's not a software issue, but I've responded to the thread you've opened. Thanks for the report!

**Closed by kjoconnor** 2016-08-08 18:47 UTC
